### ISSUE TITLE
Blue ring around edge of dim light produced by the Torch animation type

### ISSUE THREAD

**Issue by MAClavell** [dev7355608/perfect-vision#10]
Hey,

Just installed and I'm loving that proper 5e darkvision is back. However I'm seeing an issue when using the torch animation on a light. It seems that a blue ring appears on the edge of the dim emission radius. Confirmed that it is only happening with the torch animation type. Any ideas?

![TorchConfig](https://user-images.githubusercontent.com/25129246/99898616-db2c3980-2c70-11eb-9e1b-148e0c532a00.png)

**Comment by dev7355608** [comment]
It's expected. I don't want to shine dim/bright light in intersections of vision and light sources like it happens with Foundry's default dim/bright vision, because it would ruin the visuals of a lot of animated light sources. Some animated lights have darker parts like the torch light that would be destroyed, and the animation would be barely visible. Instead in intersections the light source is rendered as if it were full bright and the visuals of the animation are preserved. I'll admit it doesn't look very pretty if the animation has a dark border. I'll have to see what can done to smooth out those borders. I do want players with darkvision to see and enjoy light animations completely. Otherwise there is no point in creating animated lights as a GM if your players barely or not at all notice their effect. I hope that explains it well.

**Comment by MAClavell** [comment]
Great explanation! Yeah that is a tricky problem. The ring isn't too big a issue and I'm sure my players can deal with it to get accurate monochrome darkvision. 

Not sure if you still want this ticket open for the smoothing you mentioned, so feel free to close it if you feel it's not needed anymore.

Thanks!

**Comment by dev7355608** [comment]
I made some adjustments in v1.9.10 which reduce the blue-ring-effect somewhat.
