### ISSUE TITLE
Conflict with Border Control

### ISSUE THREAD

**Issue by Ikabodo** [dev7355608/perfect-vision#103]
**Describe the bug**
There is a minor compatibility issue with Border Control. The issue is that If both modules are activated the border shows up on top of the token instead of under it. 

**Expected behavior**
The border should appear under the token instead of above.

**Screenshots**
With Perfect Vision & Border Control
![image](https://user-images.githubusercontent.com/7766890/127859736-43fa0516-ec61-4585-989f-2cb6f847a43f.png)

Without Perfect Vision
![image](https://user-images.githubusercontent.com/7766890/127859909-36fdd5d3-9682-4af9-aab7-b79951e872bb.png)

**Environment:**
 - OS: Windows 10
 - Browser: Chrome and Firefox
 - Foundry Version: 0.8.8
 - Module Versions: Perfect Vision: 2.2.1 | Border Control: 1.2.05
 - All Modules Disabled: Yes
 - Module List if no: libWrapper dependency still active

**Additional context**
I did try managing the priorities in libWrapper, but it made no difference. 

https://github.com/kandashi/Border-Control/issues/37

**Comment by dev7355608** [comment]
I'm leaning towards leaving it as it is right now. Makes sense for the border to be rendered on top. I don't want the borders to be under the lighting layer (affected by lighting and monochrome vision) and adding a mask to it like I do with other highlight elements would cause some problems.

What you are doing with the Borders Control looks like it could be achieved by [Token Factions](https://foundryvtt.com/packages/token-factions) (was not updated for v8, but still works, and I made it compatible with PV) as well. Maybe that's a good alternative for you? Let me know.

**Comment by Ikabodo** [comment]
Thanks for taking the time to dig into this!

To me personally, the border being rendered below makes most sense, partly since that's the way Kandashi created it but I guess mostly for esthetic reasons. But I see your point, especially if it's a lot of trouble to make an exception. I also agree that it would not make sense for the border to be affected by the lightning, so a mask would be needed.

Thanks for the tips with Token Factions, but there are some reasons I've chosen not to use that, compatibility being one of them.

Again, thanks for trying. I'll have to think a little of whether to keep Perfect Vision or Border Control. :) Both are so great

**Comment by dev7355608** [comment]
I'd like to add a little bit to my reasoning: PV 2 has a separate layer system that makes it possible to render those things that should be illuminated and affected by the monochrome filter separately. This increased the performance massively, because now there's only need for one monochrome filter, and not many for each tile/token/etc in the scene. Also the monochrome effect is now more accurate, because it is calculated after lighting and not before like in PV 1. But now in PV 2 I have to separate highlight elements (grid, drawings, HP bars, status effect, etc) and render them on top: they must not be affected by the lighting and especially not by the monochrome effect: otherwise you wouldn't able to tell what the border colors are. I have also render a mask that that makes it possible to have highlight elements look like there below tokens and foreground tiles, but they are really on top. If I apply this mask to the border other tokens or foreground tiles would obscure the borders, which leads to possibly undesirable results. But I'll test it and see if it works well or not.

**Comment by dev7355608** [comment]
I tested it, and moved the border to the background (meaning I apply a mask), but on hover I render the border on top of everything. I think this way we have the best of both worlds. I like it. Let me know what you think. Try v2.5.2.

**Comment by Ikabodo** [comment]
Ah, I see what you did. Nice work! 

_Although I personally would prefer the hovering staying behind, since the only border that will show behind now is the orange one (targeted token). And the colored ones will always be on hover. But I think this might just be personal taste._

And I realize I must come of as really picky. :) Sorry about that. I really do appreciate what you do. And I'm fully ok with you picking the option that fits your own needs first.

**Comment by dev7355608** [comment]
There may be a module out there that permanently display the border, I imagine. But more importantly: If I let the border stay in the background on hover, you would never be able to see the border of a smaller token if it sits on top of a larger token for example. That wouldn't be good. Out of all the options, this one this probably the best.

**Comment by Ikabodo** [comment]
I see, I guess these are the kind of quirks that can come up from merging layers like that. Still, performance is very important so I think it's a good decision over all.
