### ISSUE TITLE
[BUG] Map notes are not affected by darkness

### ISSUE THREAD

**Issue by DarKDinDoN** [dev7355608/perfect-vision#108]
Hello,

Not sure if this is a bug, but map notes are not affected by darkness anymore.
![image](https://user-images.githubusercontent.com/1687854/128262929-d9025bb7-3f33-4885-89fe-87240673ff54.png)

Although, that might be as intended, they kinda burn my eyes with the latest release of perfect vision :)

**Comment by dev7355608** [comment]
It's intentional. All highlight elements are now above the lighting layer and no longer affected by the monochrome filter. The eye burning is not intentional though. But I'm not sure that can be fixed. I don't want to illuminate the notes and other highlight elements. Doesn't really make sense in my opinion.

**Comment by DarKDinDoN** [comment]
Makes sense :)
