### ISSUE TITLE
Combat Booster's turn markers draw on top of the token while an overlay is present

### ISSUE THREAD

**Issue by Zamrod** [dev7355608/perfect-vision#148]
![image](https://user-images.githubusercontent.com/12570777/141702651-61c9cacb-bb0b-44a5-a1fd-772a093ac69f.png)
While an overlay status effect is present on a token while using Combat Booster, the turn market is drawn on top rather than below the token. This doesn't happen if a token doesn't have an overlay status effect and it doesn't happen while Perfect Vision is disabled.

**Comment by dev7355608** [comment]
When a token has an overlay effect, it is assumed "dead" (unconscious/dead) by PV, and the token is sent to the background like a tile which allows other tokens to move into the tokens space but not be occluded by the overlay effect icon, which is with PV enabled rendered above the lighting layer but masked by foreground elements (see #112). This effects also other things like turnmarkers and auras that PV also renders on top of everything so that they remain nice and colorful and are not affected by lighting or the monochrome filter. Of course it's not impossible to fix this in theory but it would likely cause a significant performance impact. In core v9 overlay effects are going to be rendered on top like PV does in v8, but makes no attempt to fix the problem described in #112. I'll likely drop my fix in the v9 release initial, because it has problems like the one you mentioned, and try to think of a better solution while Foundry takes the blame for #112 and not PV.
