### ISSUE TITLE
Vision inconsistencies into and out of circles

### ISSUE THREAD

**Issue by dmaneyapanda** [dev7355608/perfect-vision#177]
I created a 15' circle template, centered it on a grid intersection, and set it's vision limit to 0 (apologies, the game grid doesn't match the background image which also has some floor grid, please ignore the wooden floor lines):
<img width="402" alt="template" src="https://user-images.githubusercontent.com/2231877/148103711-1a69ff4c-ebe8-4200-9784-751047bfe41a.png">
A token on the border will sometimes get a sliver of vision, which is I assume where the problem is really occurring:
<img width="383" alt="vision inside" src="https://user-images.githubusercontent.com/2231877/148103790-cf25228e-c729-4e11-a2e6-ae8260fbacb7.png">
A token on the outside cannot see the token on the inside, which seems like proper behavior:
<img width="382" alt="view outside" src="https://user-images.githubusercontent.com/2231877/148103828-cfe02257-ffe6-4b3b-8a35-49b4e56addf1.png">

Possibly there is some discussion to be had about whether creatures in grid cells which are partially intersected by the circle border should be included in the 0 sight or not, but it seems to me that for consistencies sake we should probably make it so that any token that is blinded can't see out, and anyone outside the template can't see in.  But perhaps that isn't possible given the (totally awesome!) vision occluding  rules which seem to hug the circle perfectly.   

But if anything in this example I would expect the opposite effect - the token inside the circle is probably 95% covered by the circle and should be 100% blinded, but someone from outside maybe has a 5% chance to see the token on the inside.  Instead, the token on the inside gets this weird narrow view out, and tokens on the outside can't see the token on the inside at all.

You can move the circle around (center edge, or center of the grid square) and get some other interesting effects in some of the border cells, too.

**Comment by dev7355608** [comment]
It's working as intended: the token has a narrow view out, because it could stick its head out of the darkness. The eyes of token aren't necessarily in the exact center of its icon, but somewhere in the space it occupies. The token should be visible from the outside as well, because the head or some other body part could stick out of the darkness. But the reason why it isn't visible to the outside is that visibility tests are not 100% accurate and only an approximation: only a few points within the token's space are tested, not all points in the token's space. This isn't just a problem with PV's Sight Limit. Here is an example with two tokens, a light, and no active modules: ideally the lower token should be visible to the upper token, but it isn't.

![image](https://user-images.githubusercontent.com/31905376/148106713-079bd912-f7c5-4fd3-832b-9a281b792c07.png)
![image](https://user-images.githubusercontent.com/31905376/148106741-6b4cbaf8-efea-48fd-934e-03eb0021c610.png)

With PV's sight limited areas these types of cases probably occur more frequently or at least more noticeably. Maybe the core visibility test can be improved without a large performance impact. I'll have to look into that.

**Comment by dev7355608** [comment]
In v3.3.7 both tokens should see each other now. I understand that it might still be undesirable that the token in the darkness can see out and that this token is visible to the outside in this situation. I'll have to see what can be done about that. But the first step is done.

**Comment by dev7355608** [comment]
I leave it in this state for now. I recommend to move the token slightly inward as the GM if the player shouldn't be able to see out of the darkness or be seen inside the darkness.
