### ISSUE TITLE
Fog of war out of Sight monochrome

### ISSUE THREAD

**Issue by ForrestAM** [dev7355608/perfect-vision#18]
Hello, Fist off, I really appreciate this Module and it's wonderfully well done
My only Gripe is that when you are exploring an Area and you are able to see objects in color (Player has a torch and is viewing things as normal) That after they Move on the Room they were in is monochrome when you look back in the fog of war. 
![image](https://user-images.githubusercontent.com/53906861/101821839-83a61e80-3af6-11eb-8a9a-528e82354e74.png)

I'm not sure if this is Fixable but I just wanted to make this known

**Comment by amcvfx** [comment]
This might be the same issue but with the latest version all GM vision (when a token isn't selected) is monochrome except where there are light sources. This obviously makes looking at the map difficult without colour.

**Comment by dev7355608** [comment]
@amcvfx 
> This might be the same issue but with the latest version all GM vision (when a token isn't selected) is monochrome except where there are light sources. This obviously makes looking at the map difficult without colour.

Different issue, but it works for me in v1.2.12. I fixed another monochrome related bug in v1.2.13 just now. If it still doesn't work, please open a new issue.

**Comment by Hydrall** [comment]
This was briefly working for me in version 1.3.0, using the Limit Vision feature, but now in version 1.4.0 it has reverted back to the old style; are there still plans to add this functionality in? It would be nice for "world map" scenes, in conjunction with modules like Image Fog, so you can have revealed areas still hold some color.

![image](https://user-images.githubusercontent.com/14931056/103546451-03fb3d80-4e71-11eb-8140-06427511ba17.png)

**Comment by dev7355608** [comment]
@Hydrall Check out v1.5.0 ([release notes](https://github.com/dev7355608/perfect-vision/releases/tag/v1.5.0)). So it should work again if the *Darkness Level* is 0 or close to it. Let me know if that works for you.

I likely won't change it so that the fog of war remembers which parts were explored with color vision and which parts without. Reason being it's weird to revisit an area without color vision: the vision would be grayscale but the fog of war right outside of the field of view would be in color. Also, I think, a spotted fog of war won't look so great.

I'm pretty happy with the changes in v1.5.0, which are overall probably the best solution to these fog of war issues.
