### ISSUE TITLE
Some additional features

### ISSUE THREAD

**Issue by Kawooom** [dev7355608/perfect-vision#183]
i have some ideas:

make creating vision templates possible
for example a template for nightvision or infravision you can fast choose and enable (for example when you get a special vision type from a spell). these templates could be used for the next idea.....

possibility to color or hide tokens dependend on template
for example to give tokens a red tint when somebody uses infravision (like in the predator movie) and when they dont radiate heat (like undead) hide them from infravision

vision that just show tokens
for example with a vision you can sense NPC's through a wall but cant see the room behind the wall or you can sense npc's farther away as your vision (for example detect life spell)

thats it, i think these would be some great additions that give a lot of possibilities. Thx for your work

**Comment by dev7355608** [comment]
I would like to add (programmable) condition-based/state-based visibility rules some day, but that's probably far in the future, if it ever it happens.

I'm going to close this issue, but keep those things in mind, because I want the rules visibility rules to be as customizable as possible, but I'm not sure what the capabilities will be in the end. So I cannot promise that those things will be possible.
