### ISSUE TITLE
Line of Sight

### ISSUE THREAD

**Issue by Snackpackson** [dev7355608/perfect-vision#193]
I was playing around a lot with Line of Sight and noticed that there are some discrepancies with line of sight depending on which way the token in question had moved prior to coming to its current position. This seems to be a core Foundry VTT issue but I thought I should mention it here because Perfect Vision seemed to exacerbate the implications.

The first three screen shots are with Perfect Vision activated and the last two have it deactivated. You may notice that the other token was not revealed when Perfect Vision was deactivated.

![c12](https://user-images.githubusercontent.com/84239528/149491647-21236bc3-c18c-40df-a45e-deb3f9053ee7.PNG)
![c10](https://user-images.githubusercontent.com/84239528/149491631-6998c669-48fb-4e3c-8c3d-dd174086b910.PNG)
![c11](https://user-images.githubusercontent.com/84239528/149491638-cbdf3865-d01d-4515-8219-0cd6f9c9a363.PNG)
![c13](https://user-images.githubusercontent.com/84239528/149491659-be3190af-f566-43c1-9271-eb232f9edf71.PNG)
![c14](https://user-images.githubusercontent.com/84239528/149491665-44a76252-0f5d-4382-b0ed-a9d26fa71925.PNG)

I have not tested extensively so I don't have more examples for you but I did push for a bug report for Foundry VTT version 9 regarding the line of sight discrepancy and wanted you to be aware its relation with Perfect Vision.

**Comment by dev7355608** [comment]
The origin of the line of sight polygon is slightly different depending on the direction the token was moved last. If you move a token into a space with a wall segment that is directly on the center point of the square, you don't want the token to be able to see through the wall. That's why the origin is shifted slightly in the opposite direction of the last movement. (This is core behavior, not PV).

PV uses a different test for visibility. Core tests 9 points around the token center, but PV tests the circle of the token for visibility (the reason for that is #177).
![image](https://user-images.githubusercontent.com/31905376/149517376-eca528cb-670b-4ca2-b271-a587783c52f4.png)

**Comment by Snackpackson** [comment]
Thanks for the explanation. I'd rather have them disallow movement into a space with a wall at its center.
