### ISSUE TITLE
Always have darkvision monochrome.

### ISSUE THREAD

**Issue by dmrickey** [dev7355608/perfect-vision#202]
In pf1, if it's dark, and I have darkvision, then I see black and white. Now after creating a scene, I have to turn on "saturation level"--I don't really know what saturation level is I just know that apparently I have to check it now. I just want to simply have "no light sources" = "use darkvision". 

Unrestricted vision is basically light everywhere, if there's restricted vision then foundry forces you to need a light source and/or uses bright vision to see without a lightsource--it's in this scenario that I simply want darkvision to be black and white without having to remember to check a box on the scene configuration. (I don't remember having to check that box before to get monochrome vision, can we go back to not having to check extra boxes for it?)

**Comment by dev7355608** [comment]
Saturation Level is the saturation (colorfulness) of unilluminated areas. At daylight (Darkness Level = 0) colors are at 100% saturation, but at night (Darkness Level = 1) you can't see colors anymore (0% saturation = 100% monochrome); this is the behavior if the Saturation Level box is unchecked. Unrestricted Vision Range (UVR) doesn't necessarily mean daylight, so the Saturation Level shouldn't be linked UVR, because with moonlight colors aren't at 100% saturation probably.

I assume play in scenes that are dark/at night, but you have set Darkness Level to values near 0, because the background image is very dark already. That's why you are forced to check Saturation Level and set it to 0. If I changed the default behavior of Saturation Level to be always in the checked state initially, then you would have to remember to uncheck the Saturation Level box for every daylight scene you create. The unchecked state as default makes sense, because there's probably no adjustment necessary if the background image's color and brightness are calibrated correctly for daylight; in general background images shouldn't be pre-darkened, because, if the Darkness Level is near 0, dim and bright light look almost identical and bright light is very dark.

**Comment by dmrickey** [comment]
If I have "daylight" then I don't need light sources. But my players can see beyond any available light sources then it's dark in those spots. daytime/nighttime don't play into those dark spots at all. If they player can't see it without a lightsource--but can with darkvision, then those spots need to be monochrome.

**Comment by dev7355608** [comment]
How do you set up daylight scenes? Darkness Level = 0 and Unrestricted Vision Range = On, I assume (?). But if the default was Saturation Level = 0, then you would have to change that in the settings to 1, otherwise everything that wasn't illuminated by an ambient light source would be gray, and you wouldn't want that in daylight scenes.

**Comment by dmrickey** [comment]
![image](https://user-images.githubusercontent.com/3664822/150620627-0d4b6732-b971-4f8b-bef5-8de3424f6397.png)
These are the only settings I've ever changed with regards to scene vision

**Comment by dev7355608** [comment]
So you just use Unrestricted Vision Range (UVR) for daylight/darkness? You never touch the Darkness Level (leave it at 0)? I can't link the Saturation Level by default to UVR, because UVR doesn't mean (day)light necessarily. You'll have to adjust Saturation Level at some point, because you have Darkness Level set to 0 in all your scenes if I understand correctly.

**Comment by dmrickey** [comment]
Correct, I had never touched "Darkness Level" previously--yes, it does look like they default to 0.

Can you provide a short blurb about exactly what scene settings are needed for "tokens with light see with colors, tokens using darkvision see lighted areas with color and dark areas in monochrome"?

**Comment by dev7355608** [comment]
If you check the Saturation Level box and set the saturation to 0, unilluminated areas (and darkvision) are fully monochrome regardless of the Darkness Level.

**Comment by dmrickey** [comment]
Is there any way to default new scenes to have the checked by default along with the "gm vision" defaulting to on (I'm not sure if that sticks between sessions or not, but there's no reason to see the map in darkvision myself unless I have a token selected and want to see what they see)

**Comment by dev7355608** [comment]
There's no way to change the Saturation Level default, but you only have to check just one box.

I recently changed GM Vision to not persist after a reload to remind the GM of what the scene looks like without GM Vision. You can quickly toggle it on/off with CTRL+G (default) though.
