### ISSUE TITLE
Feature Change: Blindness toggle on or off. [For Pathfinder2e]

### ISSUE THREAD

**Issue by MrChessur** [dev7355608/perfect-vision#221]
Not sure if this feature exists on other systems. Playing on PF2, game has enough rules for blinded without actively blinding token. Wondering if it was possible to put a toggle for whether blinded should cause this effect or not in the module settings.

**Comment by dev7355608** [comment]
But wouldn't you still have this problem when I add an opt-out setting? Because the system removes darkvision if your blinded, so without light sources that is effectively the same was PV's blindness. And don't you have the same problem with characters without darkvision all the time? Because they can't see in darkness at all.

**Comment by MrChessur** [comment]
I do have the same issue, I suppose. The only difference is that I have found a work around for that. I guess the issue is more in RBV implementation when combined with perfect vision. Sorry for the inconvenience.

**Comment by CarlosFdez** [comment]
This issue was closed, but to be more specific, the reason the pf2e does not blind tokens when they have blindness is because almost everyone internally voiced against it, since otherwise a person who is unconscious might as well get up and walk away because they can't see anything. Personally I've had to disable perfect vision in my own game because people who go unconcious (and thus are automatically blinded) can't see anything and had no motivation to stick around. I haven't had anyone go unconcious in many sessions, so I wasn't aware it was a thing for the longest time.

**Comment by dev7355608** [comment]
Have they been changes to the system regarding automatic blindness? When I implemented this, PF2e tried to blind the tokens by setting dim/bright vision ranges to zero. This of course is not proper blindness, but in dark scenes without light it effectively blinds the token. I just replaced this with proper blindness. It was seems to me the intention of the PF2e was it truly blind tokens with the blinded condition.

If the system removed its blindness automation, I would be open to adding a toggle for this. But if it still has it, I'm not sure how to proceed: do I override that as well if blindness automation is toggled off in PV? I don't really want to disable part of PF2e's automation.

Can't you remove the blinded condition manually of a unconscious player or does the automation immediately reapply the blinded condition? This would be my suggestion for a workaround if you want to keep PV around.

In v10 this is going to be PF2e's problem: sight limit is going to be a core feature, which gives the system the option to properly blind tokens. Consider v10 is close, I'll probably leave it as is unless the system removed its automatic blindness.
