### ISSUE TITLE
[Suggestion] Add a "Darkvision Activiation Slider" for Lighted Drawings

### ISSUE THREAD

**Issue by Shuggaloaf** [dev7355608/perfect-vision#227]
It would be nice if the lighting features of drawings could also have a "darkvision activation slider" like core Foundry does. Basically it would be as if the `Active` checkbox was unchecked when darkness is below a certain level. Or, conversely, that the drawing was only lit if darkness was above a specified level. 

I noticed a need for this when I had a scene set to night while setting up an area to be lit. I raised the darkness level of the lit drawing area to give it a dim light. However when switching to daylight, that area then looks dark compared to the natural scene lighting. 

Having a way to de-activate the lighting during daylight opens up the ability to set a lit drawings darkness level and gives the user a broader range of luminosity options.

**Comment by dev7355608** [comment]
You can disable all interior lighting with one click if you set up a interior lighting control panel (see https://github.com/dev7355608/perfect-vision#drawing-example-1-mixed-indooroutdoor-scene). Or create a macro that that sets the scene darkness and interior darkness at the same time.

Of course this could be solved by adding another option to the drawings, but I'm not sure if I want to do that: I don't want to make the UI more complicated than it needs to be. And I think the options I mentioned are good enough, though slightly less convenient. Let me know if you think otherwise / think the control panel option or macro solution is insufficient or too inconvenient.

**Comment by Shuggaloaf** [comment]
>one click if you set up a interior lighting control panel 

This is definitely useful and makes things a bit easier for some applications. 

>I don't want to make the UI more complicated than it needs to be.

Since the option is one already available for lights, and GMs will be familiar with it, I wouldn't consider it to be add more complication. Just my opinion of course. 

>Let me know if you think otherwise / think the control panel option or macro solution is insufficient or too inconvenient.

These options will definitely work, but aren't optimal. I'm hesitant to say something isn't "convenient enough" though when you're the one investing your time to develop/maintain the mod.  I also know this may be niche. Maybe because people haven't thought of using lit drawings that way, maybe not. 

Just to give you my use case, I was using the lighting not for interior but for drawing _exterior_ lighting areas. It looks more realistic than just pasting a bunch of circle lights but the real benefit is not having to have walls in areas just to block light, especially when you may not want a wall in that area. 

The issue with this usage is that since the lit drawing is an outside area, if the darkness isn't set to 0 for the drawing, then when you change the scene to daylight, the lit drawing area is now darker than normal daylight. Other lights can be set to flicker on/off at differing darkness levels and it would be nice if the drawings had the same behavior. That way they could be set to come on at, say, darkness level 70% and turn off when lower than that. The big kicker here is that I'm using the Small Time mod to auto-change from day to night. This would allow drawings to automatically turn on/off as well when using that or similar mods, macros, or just the day/night transition button. 

Sorry this got long but I wanted to give you the bigger picture so you could get an idea of what this would allow, both for scene lighting and for allowing lights to be tied to auto-scene darkness mods/macros/etc. So maybe just something to think about for the future.

**Comment by dev7355608** [comment]
> Another thought that could potentially accomplish the same thing - not sure if this is harder or easier but what about allowing the Parent to be a light?

That's not really possible because lighting drawing define the darkness level which control which lights are activated based of the darkness activation range: that would be circular.

---

The solution to this problem is an option for different inheritance behavior. Unless Override is checked, the setting of the parent is copied to the child. You want that the darkness level of child is the parent's darkness level multiplied by 0.5, for example. This way the transition would be smooth as well. Conditional activation based on the parent's darkness level wouldn't do that. I have thought about this option from the beginning, but never implemented, because it didn't want to overload the UI.

Have you tried adjusting the Darkness Color instead adjusting the darkness level of you drawings. So uncheck the Override of the darkness level and choose a color in-between the default darkness and daylight color. It's not quite the same as reducing the darkness level, but it might be an acceptable look nonetheless. With this setup no additional action is required for daylight-darkness transitions. And that would also make it possible for lights to be activated based on the scene darkness, because the darkness level of the drawings is the same as the scene's, and not fixed (lights are activated based of the darkness level of the drawings they are in).

![image](https://user-images.githubusercontent.com/31905376/103926636-78580a00-5119-11eb-983d-25c2f879aaa0.png)

**Comment by dev7355608** [comment]
I'm glad that the darkness color settings works for you. The darkness level value has an effect on the brightness of the lights as well as brightness difference between bright and dim light. So it won't look entirely the same compared to the lower darkness level with no change to the darkness color. I may expose the parameters that control the brightness of lights in a future update.

> I'm probably misunderstanding, or maybe I'm missing it, but I don't see a way to input a multiplier?

That isn't implemented. That would be the proper solution. A simple multiplier wouldn't be enough though: sometimes you would want to remap the [0, 1] range of the scene to a range of [0.25, 1] for the drawing, for example, a cave entrance that allows some daylight in. It requires some significant UI changes.

**Comment by Shuggaloaf** [comment]
>I may expose the parameters that control the brightness of lights in a future update.

That would be great!

>That isn't implemented.

OK I was wondering if that might have been a hypothetical but wanted to make sure I wasn't missing anything. 

>sometimes you would want to remap the [0, 1] range to [0.25, 1] for the drawing

THIS! That's what I opened the Issue for. My use cases is another example of that - torch gets lit at dusk. Like you said the multiplier wouldn't be enough on it's own but I figured with that and the darkness color solution that was pretty darn close. 
I didn't realize it would take significant UI changes. That's unfortunate but I can imagine now that it would be. Especially if you got into variable darkness ranges for different settings. 

Well anyway thank you for the explanations, I appreciate it. This takes care of most of my use cases and at least now you know that if you ever decide to go through with the major changes that at least 1 person would appreciate it!
