### ISSUE TITLE
[Feature Request] Complex vision angles & limits

### ISSUE THREAD

**Issue by Doresain** [dev7355608/perfect-vision#228]
Hey, amazing module! Thanks for all the hard work you put in. Prefacing this suggestion by saying I have no idea if this is possible.

Vision Angle is very tempting to use, but is awkward in practice as it doesn't account for peripheral vision and creates the awkward experience of having no awareness whatsoever outside that angle. Ideally, I'd want to specify multiple vision angles, vision radii, and sight limits to better simulate actual senses. 

Rough example. if 0° is directly in front of the token:
- Primary vision: 0-60° and 300-360° - 200ft sight limit, 0ft bright radius, 5ft dim radius
- Peripheral vision: 60-150° and 210-300° - 45ft sight limit, 0ft bright radius, 5ft dim radius
- Rear spider-sense: 150-210°-  0ft sight limit, 5ft dim radius

In v8 and before this seemed impossible, but after watching Atropos talk about the efficiency of the new polygon algorithms and how they actually get faster with limited vision angles it made me wonder...

Thanks for taking a look!

**Comment by dev7355608** [comment]
I likely won't add new vision rules features like this before Foundry v10, because new vision features are coming with v10. Once prototype 2 is released, I'll know more about the extend of these changes and how many of PV's vision features are replaced by it or need to be integrated in different way. So I'll consider adding something like this once v10 is released.

**Comment by dev7355608** [comment]
I'm not going to add this to PV. PV's focus is going to be on lighting drawings and vision limitation in V10. This feature should be separate module. V10 brings some changes that makes implementing it easier.
