### ISSUE TITLE
Perfect Vision does not apply FXMaster's core_lightning filter

### ISSUE THREAD

**Issue by Truncated** [dev7355608/perfect-vision#264]
Using FXMaster to apply lightening and Rain (top-down) to a scene map.

The Rain is not showing, but the "flashes" of lightening does. In trouble-shooting I noticed this message. I'm not sure if it has anything to do with the Rain / Weather effects from functioning yet, but I figure I can always open another issue or add detail to this if it is.

![image](https://user-images.githubusercontent.com/14208325/182904178-6efe7160-d76a-4a24-8747-4566e4fd0c93.png)

Obviously just a warning. :)

**Comment by dev7355608** [comment]
Make sure FXMaster and Perfect Vision are up to date (you can uninstall and reinstall those modules to make sure you've got the latest versions). Make sure you don't have any weather masks in the scene (drawings of FXMaster or Weatherblocker that mask weather). Make sure you don't have the *Invert Mask* option enabled (the purple mask icon in the FXMaster controls).

All FXMaster particle effect should work flawlessly with PV. PV won't receive any updates anymore for v9, because v10 is so close. Should this in fact be some kind of bug, it shouldn't be an issue in v10, because PV no longer needs to interact with weather or FXMaster.
