### ISSUE TITLE
Perfect Vision issues in FoundryVTT 9.280

### ISSUE THREAD

**Issue by Aeristoka** [dev7355608/perfect-vision#269]
![image](https://user-images.githubusercontent.com/7988297/186996509-fd124f61-bedc-49e7-99a4-4722ebc7225f.png)

**Comment by Aeristoka** [comment]
Perhaps related to https://github.com/foundryvtt/foundryvtt/issues/7940?

**Comment by dev7355608** [comment]
Fix it in 3.9.15.

Yes, it is related to this issue. I shipped the texture loader fix with PV since I discovered it because of its significance. But the backported fix in 9.280 changed some methods to #-private, which caused my fix to break unfortunately. If the methods wouldn't have changed to #-private, PV wouldn't have broken with 9.280.

**Comment by Aeristoka** [comment]
> Fixed it in 3.9.15.
> 
> Yes, it is related to this issue. I shipped the texture loader fix with PV since I discovered it because of its significance. But the backported fix in 9.280 changed some methods to #-private, which caused my fix to break unfortunately. If the methods weren't changed to #-private, PV wouldn't have broken with 9.280.

Sure appreciate you looking out for us users by having fixes like that in your Module. Excellent work!
