### ISSUE TITLE
Vision Limitation doesn't work properly with Levels

### ISSUE THREAD

**Issue by gris-x** [dev7355608/perfect-vision#280]
### Expected Behavior

I have used the Configure vision limitation option, in a daylight map (fog limiting sight to 60') 
![image](https://user-images.githubusercontent.com/73260133/188343523-172fdd18-5280-45b6-8491-2d098340638f.png)

When looking from a character with no darkvision, even when the map is in daylight, the token only sees the token adjacent (i have its darkvision vision set to 3)
![image](https://user-images.githubusercontent.com/73260133/188343579-3a48e945-c864-41a5-bf84-fff4f59d09fe.png)

When looking through a character with darkvision 60, it sees all tokens around.
![image](https://user-images.githubusercontent.com/73260133/188343666-a3f86957-ecfa-47f3-bd8e-af21fbb74a41.png)

I am expecting all tokens to have the same visibility on tokens around as the map is set for daylight, and darkvision should not be a factor to see in daylight within the range set...

### Current Behavior

Token with 3 darkvision can only see tokens withion 5 feet of them, even if the map is set in daylight

### Steps to Reproduce

set daylight on a map
have a token with darkvision set to 3
have a token with darkvision set to 60
these tokens see stuff differently when map visibility is set to 60'

### Version

v10

### Foundry VTT Version

v10.284

### Operating System

Windows

### Browser / App

Chrome

### Game System

dnd5e

**Comment by dev7355608** [comment]
I'm unable to reproduce it. Could you export the scene (right-click on the scene in the scene tab -> export to data) to json, zip it and share it with me? I don't need the assets.

**Comment by gris-x** [comment]
[fvtt-Scene-village.zip](https://github.com/dev7355608/perfect-vision/files/9487662/fvtt-Scene-village.zip)
Here it is, hope this helps!

**Comment by dev7355608** [comment]
Fixed. Update Levels.

Thanks for the report!

**Comment by gris-x** [comment]
Seems like it was fixed with Level but I do get something weird still.
If I set the sight limit to 60' for everyone, those with darkvision seem to add 60' to the range, for a vision up to 120' .
Same settings as above, just tokens with darkvision see farther than those without,

Is the intent not to limit all vision to 60' for all?

**Comment by dev7355608** [comment]
Example:
> Sight Limit: 40
> Basic Sight: Infinity

This would mean than a token with 60' darkvision (basic sight) can see within its vision range of 60' without any restrictions. After 60' the Sight Limit applies, because at that point the token sees with the standard eyesight. The sight ray hasn't lost any energy for the first 60' yet though, because the Basic Sight limit is set to Infinity. So the token can see another 40' after that, which adds up to 100'. Token without darkvision can only see 40'.

If you configure it like this:
> Sight Limit: 40
> Basic Sight: 60

Then tokens wouldn't be able to see more than 60' with darkvision.

It might be a bit weird at first, but if you think about it in the context of locally defined areas of Vision Limitation, it makes sense that it works like that. For example, an area of magical darkness: normal sight wouldn't be able to go through it, but magical darkvision would. But if you have magical darkvision, your normal eyesight goes through it unimpeded as well within the range of magical darkvision. If it would be blocked, a token with X' magical darkvision wouldn't be able to see further then X' if it stands in an area of magical darkness, even if the magical darkvision reaches far enough that would allow the token to see out of the magical darkness. My interpretation of magical darkvision was always that, if the token magical darkvision range is far enough to see through or out of the magical darkness, it would be the same as if the magical darkness didn't exist.

**Comment by gris-x** [comment]
Understood! thanks a bunch for the details and all the work on this!
