### ISSUE TITLE
Vision Limitation doesn't appear to function

### ISSUE THREAD

**Issue by Zamrod** [dev7355608/perfect-vision#284]
### Expected Behavior

With Vision Limitation turned on tokens shouldn't see anything beyond the range.

### Current Behavior

There is no difference in sight between vision limitation turned on or off unless you also restrict the basic vision detection mode.

### Steps to Reproduce

1. turn on Vision Limitation and enter a restriction into any or all of the vision modes

### Version

v4.0.5

### Foundry VTT Version

v10.284

### Operating System

Windows

### Browser / App

Native App (Electron)

### Game System

dnd5e (2.0.2)

**Comment by Zamrod** [comment]
It doesn't work for normal eyesight either. It doesn't restrict anything at all. To restrict normal eyesight you need to apply a limit to the basic vision detection mode and it ignores the value in the vision mode entirely.

How I expected it to work, even if that isn't the way it does currently is that if you put something like 5 ft into the vision restriction that all "Vision based" detection modes would be limited to the same amount (Darkvision, Basic Sight, See Invisibility). but you could override individual ones using the individual detection modes.

**Comment by dev7355608** [comment]
> It doesn't work for normal eyesight either. It doesn't restrict anything at all. To restrict normal eyesight you need to apply a limit to the basic vision detection mode and it ignores the value in the vision mode entirely.

The scene is filled with red light. The token is only able to see only 10 ft with normal eyesight. The token's vision range was nonzero, the token would have Darkvision (Basic Sight), which wouldn't be limited in this configuration (Basic Sight Limit is Infinity) and the token would be able to see further.
![image](https://user-images.githubusercontent.com/31905376/188763192-a1d768f6-9ef6-44bf-9a81-05bb52b1e893.png)

> How I expected it to work, even if that isn't the way it does currently is that if you put something like 5 ft into the vision restriction that all "Vision based" detection modes would be limited to the same amount (Darkvision, Basic Sight, See Invisibility). but you could override individual ones using the individual detection modes.

I planned make it so that unless a Detection Mode limit is specifically set it defaults to the type-based limit. But I wasn't sure how to that without cluttering the UI more: the Lighting Drawings' Vision Limitation UI already has the Override checkboxes.

**Comment by dev7355608** [comment]
I added buttons to the UI that copy the limit to all detection mode limits of the same type and added some clarification to the description of detection mode limits in 4.0.11:
![image](https://user-images.githubusercontent.com/31905376/189456318-9b9d6d42-ab0f-4cc3-9fef-7ce40968af0c.png)

Let me know if you still have questions, suggestion, or still think that there's something wrong.

**Comment by dev7355608** [comment]
As of 4.0.17 the FOV (polygon defined by Vision Range and LOS) of the token restricted based on the Basic Sight limit alone (and not based on Sight Limit too). Pre 4.0.17 the FOV could have appeared larger than it actually was if the Basic Sight Limit was lower than Sight Limit. Not sure if that's what you initially experienced or something else. But I assume it was either a misunderstanding of the configuration or the FOV issue I fixed in 4.0.17. Should something still not work as expected, let me know.
