### ISSUE TITLE
D&D Vision Modes and interactions

### ISSUE THREAD

**Issue by ducky00** [dev7355608/perfect-vision#293]
### Description

Hey, I had a few ideas to further the support for the D&D system that I think are worth mentioning here.

Devil's Sight is probably the only one that core doesn't support right now

But sneaking is the one I think would be the most helpful one. You could roll a sneak test and the player or GM would receive a pop up asking if they want to use that roll to hide, pressing yes the token gains a new "Hiding" condition. Tremorsense would naturally perceive it anyways, but the passive perception of all tokens could come into play to check if they would see it or no. If they make a perception test instead, use that roll rather than passive perception to check if they spot hidden tokens or not.

**Comment by dev7355608** [comment]
PV won't include system-specific features anymore. The scope of PV is now limited to Lighting Drawings and Vision Limitation mostly. What you suggest should be part of a module specifically for the 5e system that offers more advanced and automated vision/detection modes, because PV wouldn't be required to make that possible (except for proper devil's sight magical darkness interaction you'd need PV's Vision Limitation feature, but that would be optional essentially). I might experiment and create such a module in the future, but no promises.
