### ISSUE TITLE
Is it possible to have sight limit back?

### ISSUE THREAD

**Issue by DrYima** [dev7355608/perfect-vision#295]
### Description

Hello, I recently migrated to v10 and was trying to limit a token's vision, _regardless of light_, but I cannot find a way to do so, I can only change how much a token can see without light when before I could limit is its sight completely. I am not sure if this is a bug or just a lost feature, so ill drop this here hoping you can let me know. 
Thank for the great work regardless, ill just work around it with the other option you give with the module if I wont be able to outright limit the sight.

**Comment by dev7355608** [comment]
What you knew as *Sight Limit* in v9 is now *Vision Limitation*. You'll find in the scene's lighting config, token light config, ambient light config, and template config, where you previously had *Sight Limit*, but now there are much more options available, that allow you to not only limit vision, but also detection modes.

In case you're looking for *Sight Limit* in the token's vision config, that's gone, because that was mostly used for blindness; core does that now in v10 automatically, so it would have been a partial overlap. But if you just want to limit vision in the entire scene, set that in the scene's *Vision Limitation* config.

**Comment by DrYima** [comment]
Yeah I did find that, but I want to only limit the sight of *one* token, not of every token in the scene

**Comment by dev7355608** [comment]
What's scenario, where you want to set a nonzero sight limit for one particular token only? I removed it because I couldn't think of a common use for nonzero sight limit on a token, where you wouldn't want to set a scene sight limit.

**Comment by DrYima** [comment]
I suppose it is a very niche thing, one of my player wanted to play a fighter who was blind but with 10 feet of blindsight, with the previous build I was able to have the token sight represent that as well, setting the sight limit to 10.
But if you believe it too much of a commitment to reimplement this so be it, I did sort of find a work around using the tremor sense special vision and sense all detection, the only thing is that when there is light the token does see normally over the 10 feet, but yeah, as I said, if it's too much of bother I can suck it up haha

**Comment by dev7355608** [comment]
I think that might be a job for V10's Vision/Detection Modes. If your system it D&D 5e, check out the *Adequate Vision* module: it just recently added Blindsight.

**Comment by ucgm** [comment]
> I think that might be a job for V10's Vision/Detection Modes. If your system it D&D 5e, check out the _Adequate Vision_ module: it just recently added Blindsight.

_Adequate Vision_ did recently add the 'blindsight' detection mode, it doesn't quite do the same thing as this request though. It will highlight tokens within range, and looks cool if you make the token have the 'blind' condition.

The issue is that you either make the token blind and they can't see the map well:
![image](https://user-images.githubusercontent.com/115857233/195968550-7891529d-5b7e-4341-a7b2-f062f6485c2b.png)

...or you don't make them blind, and they can see normally in lit areas:
![image](https://user-images.githubusercontent.com/115857233/195968585-a8edb658-2c0c-44b7-a648-17633bea0264.png)

This doesn't quite fit with my, or if I'm reading it right, DrYima's, interpretation of the blindsight rules:

> A monster with blindsight can perceive its surroundings without relying on sight, within a specific radius.
> Creatures without eyes, such as grimlocks and gray oozes, typically have this special sense, as do creatures with echolocation or heightened senses, such as bats and true dragons.
> If a monster is naturally blind, it has a parenthetical note to this effect, indicating that the radius of its blindsight defines the maximum range of its perception.

Note the monster can perceive its **surroundings**. My interpretation is this includes the physical space it's in, not just other creatures. How do we represent this in VTT? Well, probably just show the map within range, maybe ignore ambient lights and have a set illumination level for the perceived distance.

This is represented well by _Perfect Vision's_ sight limit:
![image](https://user-images.githubusercontent.com/115857233/195968884-76ca5b82-5d64-444e-8cf9-e20a613bd782.png)

Is it the right place for it to go? I don't know, but you're almost there with the global setting being per token.

**Comment by DrYima** [comment]
Thank you all for still entertaining my request haha

but yeah to let ucgm know, I do want the token to see its surrounding and not only creatures.
My player is already sad it can't see the whole of the maps I use and cutting away those 10 feet would be very sad haha (we are working on a way to fix is partial blindness but that is beside the point of my post)
And I do think blindsight like its done in _Adequate Vision_ is already done well enough in v10 with the sense all detection mode, there is just that caveat that there is no option to have the token not see even when there is dim or bright light.

**Comment by NinjaPirateBob** [comment]
This would be a useful feature for me as well, I'm running a Shadowrun game and I have a Camera actor I can drop on the map where there are cameras, the Hacker can view these feeds when successfully hacking so it's really simple for me to just give them control of the actor temporarily so they can get a sort of "overwatch" view and communicate with their team. This frees me up to control NPC tokens on the map and do things that not all players can see. I have a lot of cameras with different vision modes and vision "cones" that are only useful within a certain range so it would be nice to set a hard limit on all sight for the Camera tokens so the blindspots will actually be unknown areas for them.

**Comment by dev7355608** [comment]
Regarding blightsight the problem lies with how vision and detection modes were designed in v10: basically the only sense that can perceive surroundings is darkvision (basic sight). All other senses (detection modes) can perceive only tokens. I'm looking into how to make rules-accurate blindsight work. It very likely requires a hack.

@NinjaPirateBob Maybe light sources with Provides Vision enabled might be better suited as cameras. It reveals the area to everyone though and it sounds like that's not something you'd want, but at least this way it only reveals within range.

**Comment by sanpats** [comment]
In Savage Worlds, because different race have different vision range at a given Light condition.

**Comment by sanpats** [comment]
For example, in Dark but not pitch black condition, humans have 20 yards sight limit, elves with Low Light Vision have no limit, dwarf with dark vision can see up to 40 yards.

**Comment by mnoreke** [comment]
I have a scenario where I need to limit just the one token to a vision range:

A player has chosen to play an undead elf, and as a result of their deteriorating body, their vision is limited to 120 ft. regardless of lighting conditions.

Could this be added back in? I would hate to give them monochromatic or something else instead to limit their vision as they don't get to enjoy all the maps that way.

**Comment by joshuadotbio** [comment]
I also have a scenario that needs a sight limit on just one token. One of my players has a character who is blind but has the ability to "see" everything within ten feet. In Foundry VTT version 9, I was able to accommodate that perfectly using the per-token sight limit feature of your Perfect Vision module, but since the update that's been impossible.

**Comment by LeoHuntsman** [comment]
So wait, what does the "Configure Vision Limitation" do in the token settings, then? I thought it would , as the title implies, limit sight. Shouldn't the token not be able to see outside the green line?
![image](https://user-images.githubusercontent.com/113218754/201542940-8d58c364-06ae-4b05-be42-030d855ce5a3.png)

**Comment by dev7355608** [comment]
> So wait, what does the "Configure Vision Limitation" do in the token settings, then? I thought it would , as the title implies, limit sight. Shouldn't the token not be able to see outside the green line?

@LeoHuntsman Vision Limitation in the token config is part of the token's light settings and allows you to configure the vision limitation the token's light source provides.

**Comment by LeoHuntsman** [comment]
@dev7355608 That makes sense, thanks for clearing that up. Just to confirm and summarize, there is no way currently to limit what that token sees beyond that 60ft line in an otherwise lit scene?

**Comment by dev7355608** [comment]
@LeoHuntsman It's not possible to set the range of sight (light-based perception) of a token at the moment. You can limit sight with templates, light sources, drawings, or in the scene settings, but these limits affect all tokens.

**Comment by dev7355608** [comment]
Sight Limit is back in 4.1.0! It's not quite the same as in v9 tough: it cannot be used to reduce the darkvision range. So if you token has 30 feet in darkness and 0 in light, it will be able within those 30 feet; in v9 Sight Limit would have reduced darkvision to 0.
![image](https://user-images.githubusercontent.com/31905376/204005702-6c88f329-c7ed-4643-a2ae-b0e3485462bf.png)
