### ISSUE TITLE
Perfect vision not showing up under configure game settings

### ISSUE THREAD

**Issue by Darkstar47** [dev7355608/perfect-vision#297]
### Expected Behavior

To be able to edit the Perfect vision settings under Configure game Settings

### Current Behavior

After enabling  the perfect vision module it does not show u
![Screenshot 2022-10-17 104723](https://user-images.githubusercontent.com/43366057/196132733-af4e4291-ceba-4b96-bfbb-7f90aa389915.png)
p under Configure Game Settings

### Steps to Reproduce

1. Install Module
2. activate Module
3. Check to see if Module is active under Configure module settings
4. It is not there

### Context

I have tested this on a clean dnd5e world with only Libwrapper module enabled to rule out all other  module interference.
I have removed the module restarted foundry and installed again and it is still not showing the module settings

### Version

v4.0.29

### Foundry VTT Version

v10.288

### Operating System

windows 11

### Browser / App

Native App (Electron)

### Game System

dnd5e

**Comment by dev7355608** [comment]
Since introduction of Vision/Detection Modes in V10, vision rules and darkvision have been removed from PV; that's all core now. So PV doesn't have game settings at the moment. If you don't use PV's Lighting Drawings or Vision Limitation (Sight Limit) and only have been using PV for darkvision, you may uninstall it. You can configure darkvision in the token's vision config. The Adequate Vision module might also make your life easier and offers some enhancements specifically for dnd5e.
