### ISSUE TITLE
Odd white rim with non-B&W tinting

### ISSUE THREAD

**Issue by mkahvi** [dev7355608/perfect-vision#3]
So I tried to do nostalgia trip by making the monochrome darkvision reddish, but it's causing a weird white ring at the border of the darkvision and normal vision region.

![Screenshot 2020-11-17 072637](https://user-images.githubusercontent.com/8120158/99350511-3d6af000-28a7-11eb-81f6-26633f794966.png)

Mildly related, I kinda wish there was more of a gradient to make the transition less harsh, but I don't want to make separate issue for that right now.

Environment:  
> FVTT 0.7.7  
> PF1e 0.75.13

**Comment by DarKDinDoN** [comment]
Same her but with the default color.  
On the screenshot token is selected and has bright vision:
![image](https://user-images.githubusercontent.com/1687854/99568011-2d4e3000-29cf-11eb-9f9f-081ede85155f.png)

**Comment by dev7355608** [comment]
@DarKDinDoN That's actually a different issue and it's intended. I don't want to shine full dim/bright light in intersections of vision and light sources, because it would ruin the visuals of a lot of animated light sources. In intersections the light source is rendered as if it were full bright and some animated lights have darker parts like the torch light above. I'll have to see what can done to smooth out those borders. It isn't very pretty.

@mkahvi Could you please check if you still get those white rings in v1.2.2? I didn't notice any.

**Comment by DarKDinDoN** [comment]
@dev7355608 Yeah noticed it's working great with other light sources.
Unfortunately "Blurred" torch from Community Lighting (https://github.com/BlitzKraig/fvtt-CommunityLighting) is the best kind of light sources for fantasy :/

**Comment by mkahvi** [comment]
PV 1.2.3. I can still see it there, but it's so faint that it hardly matters.  
![Screenshot 2020-11-19 085843](https://user-images.githubusercontent.com/8120158/99632182-78a32580-2a45-11eb-9797-dbb09911d9b8.png)

And I can't see it at all on one of my monitors (which has worst color reproduction quality of all).

I'll close this issue, as wanting anything better is just nitpicking IMO (still desirable tho).

**Comment by dev7355608** [comment]
@mkahvi I realized what was causing the white glow. Fixed it in v1.2.5.
