### ISSUE TITLE
drawings not made invisible when lighting is enabled

### ISSUE THREAD

**Issue by Psychotopia** [dev7355608/perfect-vision#318]
### Description

the option to not disable the visuals of a drawing when you enable lighting effects
allowing the following
![image3](https://user-images.githubusercontent.com/75271642/206811454-a3c961ad-78f3-43a4-85e5-ad9ae491fcec.png)

### Context

ive been trying to use the drawing features youve added to make smoke clouds, but when enable the lighting settings for a drawing it turns off there visuals meaning you can no longer see the smoke cloud texture the drawing had examples below

![image1](https://user-images.githubusercontent.com/75271642/206811463-01ca0b58-1ac7-4ad7-920f-e10230a02a78.png)
lighting enabled smoke cloud not visible vision restricted by smoke cloud
![image2](https://user-images.githubusercontent.com/75271642/206811464-a1e483e9-63a1-4bdb-8244-3f5675f01b03.png)
lightning disable smoke cloud visible vision unrestricted by smoke cloud
![image3](https://user-images.githubusercontent.com/75271642/206811454-a3c961ad-78f3-43a4-85e5-ad9ae491fcec.png)
two seperate drawings layered over each other allowing players to see the smoke cloud restricting there vision

i intended to use advanced drawing tools editiable polygons to make dynamic smoke clouds that used this module to restrict vision, two of my players are focused around vision denial one an opaque darkness generator and the other creates large moving smoke clouds, while i can still theoreticaly do this it requires me to copy the drawing so i have one for vision and for visual then delete one edit the main drawing and then copy again every time i alter the shape of the cloud

edit:
also is it possible to make a specific token not effected by a specfic vision restricting drawings as my players character can see through there own smoke/darkness but not each others

**Comment by dev7355608** [comment]
I wouldn't recommend to use lighting drawings for this. The reason is that, if you ever use other lighting drawings in your scene, the drawing of the smoke cloud will override the lighting (darkness level etc) defined by another drawing. So assume you have a lighting drawing with Darkness Level 1 for the interior in a building but outside the Darkness Level 0 (scene config); if you then spawn the drawing for the fog in the interior, then this drawing would override the Darkness Level to 0, which it inherits from the scene config, and would brighten the interior. For temporary vision limitation templates (or light sources if it is magical darkness) is the right choice. Templates are of course more limited shape-wise.

Another minor issue would be that drawings are rendered below tokens. So the token would appear to be above the smoke instead of in it.

**Comment by Psychotopia** [comment]
im using vision limitation instead of darkness level so hopefully the darkness levels should bother me at all, ive played around with templates and they are to limited in shape and functionality to use, my players will be using the smoke from the start of battles to the end so its going to be all most permenant from round one to the end of the fights

![image](https://user-images.githubusercontent.com/75271642/206824378-986f6467-d26a-4ea5-93c8-1f0216c65b1c.png)
is it to hard to add an option to not hide the drawing while enabled?

**Comment by Psychotopia** [comment]
you are kidding me i refreshed so many times to check if the first one had posted then the moment i do the second one its there

**Comment by dev7355608** [comment]
I added a flag that makes the drawing visible in 4.1.9. There's UI for this setting at the moment, so you need to change it with a script macro. For example:
```js
// Select drawing(s) and then execute this to make them visible
canvas.drawings.controlled.forEach(d => d.document.setFlag("perfect-vision", "visible", true))
```

**Comment by Psychotopia** [comment]
Awesome thank you man i really appriciate it.
