### ISSUE TITLE
Allow showing sequencer animation on templates with sigh limitation

### ISSUE THREAD

**Issue by pgervais70** [dev7355608/perfect-vision#333]
### Description

I’m working on Fog Cloud spell and I have a AA setup on it that displays a fog sequencer effect for it. 
If I set sight limitation to 0 on the template. The tokens inside don’t see anything and the tokens outside just see a black section where the template is positioned. It would be nice if the sequencer animation could be visible. Something similar to terrain wall.

**Comment by dev7355608** [comment]
What you probably want to do it increase the scale of the effect that is attached to the template so that a token from the outside can see the edge of the fog to be able to tell that this is fog and not a wall.
![image](https://github.com/dev7355608/perfect-vision/assets/31905376/cc5d4452-b996-4275-a377-8a34118b2828)

There might be an option to render the entire fog effect above the fog of war layer such that is visible at all times like the template itself. Perfect Vision doesn't have any control over how the effect is rendered tough.

**Comment by pgervais70** [comment]
Thanks, I will try to play with the different options in sequencer to find one that satisfies my need.
