### ISSUE TITLE
Templates and others

### ISSUE THREAD

**Issue by DarKDinDoN** [dev7355608/perfect-vision#50]
Hello,

Thx for that awesome module that finally fix the vision!

Would it be possible to also hide templates and modules like turn-marker (https://github.com/kckaiwei/TurnMarker-alt) when the character doesn't have the vision (because out of "vision range" or because there is a wall blocking the view)

**Comment by DarKDinDoN** [comment]
TurnMarker just got an update about that.
Only templates are now displayed out of vision range!

**Comment by DarKDinDoN** [comment]
With the latest update, it's now working when the user has vision and didn't reveal the area.
But if a template is placed in an area that was previously revealed by the token, the template is still visible through the fog of war.

**Comment by dev7355608** [comment]
Turn Marker tried to hide its markers before the update, but it wasn't working properly. I fixed that.

In v1.6.2 the templates are now restricted to line-of-sight but not the grid highlights. Otherwise a player would have trouble placing the template. Token Magic and other modules have an option to hide these highlights. Templates are never really hidden though, because you see all of them when you select the measurement controls even if you don't have the ownership.

**Comment by dev7355608** [comment]
> 
> 
> With the latest update, it's now working when the user has vision and didn't reveal the area.
> But if a template is placed in an area that was previously revealed by the token, the template is still visible through the fog of war.

If it's not related to the grid highlights, send me a screen shot. Also I don't add the filter to templates without textures at the moment: the template outline might be showing because of this in the fog of war as well.

**Comment by DarKDinDoN** [comment]
![image](https://user-images.githubusercontent.com/1687854/104770394-cbad0680-5770-11eb-8ee5-fb3cf46e2b9d.png)


Hard to see on the image. But you can see the highlighted squares as well as the outline

**Comment by dev7355608** [comment]
Fixed in v1.7.0. I also changed it so that templates that the user owns are still visible in the fog of war.

**Comment by DarKDinDoN** [comment]
@dev7355608 Is it intended that as the GM I can see the templates in the fog of war when I click on a token to get its vision?

**Comment by dev7355608** [comment]
@DarKDinDoN Yes. I think that should make it easier for the GM to keep track of the templates. But let me know if you think there's a good reason to not show them.

**Comment by DarKDinDoN** [comment]
@dev7355608  Well if the GM clicks on a token, it is to get its vision. Templates are part of it.
If the GM want to globally see templates, he can just deselect any token. As the GM i don't want to think about if that template is in my line of sight.
What do you think?

**Comment by sharkbruhaha** [comment]
I second this

**Comment by dev7355608** [comment]
Users (players) always see the templates that they own/placed in the fog of war, because they (or a character they control) know the templates are definitely there. Templates are owned by users (players) though not by tokens. So it isn't quite clear what templates should be visible if a GM selects a token. They are basically four options:

1. All templates
2. All templates owned by the GM or any other GM
3. All templates owned by the GM
4. No templates at all

(3) doesn't make much sense, and (2) is always preferred over (3). But since the GM can take the perspective of PCs as well (1) makes more sense than (2). So it basically comes down to (1) vs (4): Should the GM always see all templates because they know about all of them, or shouldn't they see them because they can simply deselect the token if they want to see all templates.

I opted for (4) because fog of war is also per user not per token, and it makes it easier for a GM to avoid moving a token into a template area, that is, easier to plan the movement while having the token selected.

Technically, there's no real advantage for the GM to not see the templates, but it seems like the real issue that the standard fog is terrible, and it's sometimes quite difficult to tell if it's fog or in line of sight, right? Let me know.

**Comment by sharkbruhaha** [comment]
I vote #4

**Comment by DarKDinDoN** [comment]
@dev7355608 Ah I see now. Templates are not linked to characters but to players. Hmm.

It's either:
1. All templates placed by the GM but also placed by the characters
4. No templates, even the one placed by the GM

No template could be weird. Like walking into a template without knowing.
I would vote 1 then. I think, that's what you meant (no 4)

**Comment by dev7355608** [comment]
Ah yes, I meant (1). I think a lot of GMs don't enable token vision for monster tokens anyway for the simple reason to be able to see the entire map even if a token is selected. So it's probably best not to restrict the vision further for GMs that use token vision for monsters, I suppose.
