### ISSUE TITLE
Daylight color doesn't affect bright light

### ISSUE THREAD

**Issue by Zamrod** [dev7355608/perfect-vision#52]
Any daylight color you set will go away anywhere on the map you have bright vision.

For example, if you have a grey map with global illumination set to Dim Light then anyone who has Dim Vision will see orange outside of their dim vision but grey inside the dim vision. If you set global illumination to Bright Light then the entire map is grey, ignoring the colors.

This doesn't seem to make sense. If the sun is bright red then turning on bright global illumination shouldn't remove the sun's color.

**Comment by Zamrod** [comment]
I understand that this is likely a side effect of multiplicative blending. Multiply all the light together and you get white. Just not sure that's how it should work.

**Comment by dev7355608** [comment]
Bright light is always white: that's how Foundry works at the moment. I think I should get rid of Dim/Bright settings for Global Illumination entirely, and just have it be what now is Scene Darkness by default. And maybe tweak scene light a little. Probably for the best.

**Comment by Zamrod** [comment]
> Bright light is always white: that's how Foundry works at the moment. I think I should get rid of Dim/Bright settings for Global Illumination entirely, and just have it be what now is Scene Darkness by default. And maybe tweak scene light a little. Probably for the best.

I would prefer not. I really like the short hand of always having 50% light or 100% light across the whole scene. Too many adventures just say "The area is dimly lit" or "The area is brightly lit" and being able to easily select these is extremely useful.

I like the level of light being unrelated to the darkness slider.

**Comment by dev7355608** [comment]
I'll probably add a new light type as I suggested [here](https://gitlab.com/foundrynet/foundryvtt/-/issues/4341) that makes it possible to achieve the same results once I remove the Global Illumination Light setting. This way we get even more options as before, because we have a real light source that controls the global illumination light: we can select custom light effects etc, and even place multiple light sources across the map to illuminate only the areas we want to and not the entire map.
