### ISSUE TITLE
Dim vision in Dim Light and Scene Darkness (monochrome)

### ISSUE THREAD

**Issue by GabrielOsvair** [dev7355608/perfect-vision#72]
When a token that has dim vision is in a scene with global illumination scene darkness and darkness level 1, according to the rules of D & D5 and it should have a color vision (because dim vision + dim light = color vision).
Or, the global dim light illumination should be monochromatic, so that the player could see everything in the dark, and whoever has vision in the dark "see the colored dim light".

*Note: If I have misinterpreted the rules of wrong vision please let me know, or if this is an expected behavior and there is no global dim light illumination (as on a full moon night in the forest, which is gray but is still possible to see).*

**Comment by GabrielOsvair** [comment]
Imagine the following scenario: It is a full moon in a flower and the map has a gray global illumination, everyone can see the monochrome map but those with dim vision can see this colored area.

This is almost achieved with global scene darkness lighting and darkness level at 1, but those who have dim vision still see gray, but lighter.

Do you have the option of adding an option or type of view for this? Or do I already get this setting?

Anyway, thanks for the quick response, I love this mod!

**Comment by dev7355608** [comment]
You can modify the *Vision Rules* of tokens with darkvision in those moonlight scenes: select *Custom*, and change *Dim Vision in Darkness* to *Dim Light* instead of *Dim Light (monochrome)*. Or change it in the settings globally and then switch it back for other scenes.

I won't make other options at the moment to make this possible. I plan to remove the Global Light setting with the stable 0.8.* release and redesign it.
