### ISSUE TITLE
Actual Fog of War

### ISSUE THREAD

**Issue by kisnney** [dev7355608/perfect-vision#83]
Why did you remove it? Do you intend to bring it back? I really liked it.

**Comment by dev7355608** [comment]
It didn't really fit in Perfect Vision, I think, and I was too lazy to add customization options, which it needed. Since I basically copied the fog effect of FXMaster, this feature could be added to FXMaster perhaps. Maybe I'll release a separate module for this one day, but I can't promise anything right now.

**Comment by kisnney** [comment]
Ok thank you. It would be nice if you added this info to the main page. I didn't know about this feature of FXMaster.

**Comment by dev7355608** [comment]
It isn't a feature of FXMaster. I just reused the fog effect of FXMaster that covers the entire scene and restricted it to the fog of war area. I'll contact the author of FXMaster and propose this feature.

**Comment by kisnney** [comment]
Thank you!
