### ISSUE TITLE
Blur on web-browser when zoomed out

### ISSUE THREAD

**Issue by GladAlibi** [dev7355608/perfect-vision#84]
When using Perfect Vision on a web-browser the scene and any tokens all lose quality/ become blurry. A few people who use foundry I know all zoom out on a browser as a means to decrease the default Foundry UI (which apparently cant be done natively as of yet). 

Unfortunately this seems to lead to these blurred tokens and scenes exclusively when using the Perfect Vision mod.

Worth noticing the very first time you turn on the Perfect Vision mod and then zoom out the image all retain their quality. At any refresh or loading of foundry again will lead to the images being blurred. As many web-browsers remember a specific websites zoom preferences, it becomes annoying to let foundry load, zoom back to regular 100% zoom view, refresh foundry, and then zoom back out to the preferred distance to fix this. And of course, then having to redo these steps every time you access or accidentally refresh Foundry.

And FYI this occurred on Foundry 8.6 and now on 8.7. Tested on the newest (1.9.7) and previous versions of Perfect Vision. Using the latest dnd5e System. I have tried this with and without various mods, with no impact. And I have tested on Edge, Chrome and Firefox.  And here is a imgur link to a with and without comparison: https://imgur.com/a/l2gLkq2 (need to expand to actual size to accurately compare)

**Comment by dev7355608** [comment]
I'm aware of this issue. It's actually multiple bugs in pixi.js that makes it difficult to support browser zoom. This is not a problem exclusive to Perfect Vision, but with it probably most noticeable, because it adds filters everywhere. And I try to play it safe to ensure other filters don't fail miserably. But I always rounded the filter resolution down to the next safe resolution (powers of two). I am going to change that in v1.9.8 and round up from now on. This can decrease performance (depended on the zoom level) compared to 100% browser zoom, but the quality shouldn't be affected anymore. Let me know if you still notice quality issues.

Also Foundry itself doesn't make an effort to support browser/OS zoom or retina displays at the moment with respect to filters (but you would only notice it when browser-zooming in). I have some patches in Perfect Vision to correct that. But until pixi.js is fixed, it can't be properly supported. I expect the fix in the next pixi.js release or soon after. Not sure though, when this pixi.js release makes it into Foundry though.
