### ISSUE TITLE
Animated light sources cast darkness in Foundry 0.8.6

### ISSUE THREAD

**Issue by David-Zvekic** [dev7355608/perfect-vision#85]
A lightsource that creates animation in 0.7.10 or without Perfect Vision in 0.8.6 will cast light and improve illumination.  In 0.8.6 with Perfect Vision, the same animated light source casts darkness out to the dimlight range, and then casts light to cancel its own darkness.  The darkness will even darken the 'Bright Vision' of other tokens.

Notice the images : The light source is the white cloaked figure on the left, pulsing white light .  Vision is from the perspective of the selected token who has bright vision.

Perfect Vision Installed:
![PerfectVisionInstalled_SelectedToken has bright vision](https://user-images.githubusercontent.com/32999490/122874196-b54b3e00-d300-11eb-9860-625e37272e30.png)

Default Vision 0.8.6 (but will also work on 0.7.10 with Perfect Vision)
![DefaultFoundryVTT_SelectedToken has bright vision](https://user-images.githubusercontent.com/32999490/122874208-ba0ff200-d300-11eb-9572-d945314f1f13.png)

**Comment by David-Zvekic** [comment]
Also, for the record, the same issue exists in Foundry 0.8.7.

**Comment by dev7355608** [comment]
Perfect Vision is not supposed to work like shown in the second picture (it shouldn't be like that in 0.7.10 either). The reason is that this ruins light source animations for players with darkvision: they can hardly tell whether the light is animated or not, everything is full bright. Perfect Vision changes that: instead of making it full bright, you see the light as if it were configured as bright light. Depending on the light animation type it might get very dark, even if technically it should be brighter. But that's the trade off. I think it's more important that the players can enjoy the light animations the GM set up.

Without Perfect Vision:
![without_pv](https://user-images.githubusercontent.com/31905376/122944530-31cd3380-d378-11eb-8bd4-1a56f9597233.gif)

With Perfect Vision (Vision Rules = *Foundry VTT*):
![with_pv2](https://user-images.githubusercontent.com/31905376/122948483-3ba46600-d37b-11eb-856b-8fa025db7d15.gif)

With Perfect Vision (Vision Rules = *D&D 5e*)
![with_pv](https://user-images.githubusercontent.com/31905376/122949510-00566700-d37c-11eb-9321-f28b18823da2.gif)

**Comment by David-Zvekic** [comment]
Based on your information I checked and it seems I was mistaken.  Because
in my 0.7.10 Alien game, where I frequently use pulse effects no character
has dim or bright vision so I didn't see this effect before. In my D&D5e
game, the map has a white background and I never use the pulse effect, so
it wasn't so obvious.

I was mistaken,  the same behavior exists in both versions of FoundryVTT.

With that said, if your algorithm is conducive to easily implementing this,
do you think you would ever be open to making this feature a numerical
setting between 0 and 10 (or on/off)  ('Light Animation Crushing') so the
GM can control it on a system or scene basis?
OR even more powerfully on a per light source basis. You can make light
visible in case 1 by giving the light a color. This would give the GM full
control.

Anyway.. since the feature actually works as you intend it to work, and its
the same on 0.7.10 then I consider the issue closed.

Thank you!  And great work!

**Comment by dev7355608** [comment]
I made some adjustment in v1.9.10. This also solves the "blue-ring-problem" for the most part. I probably won't add a setting for this, because it would be too confusing, I think: I want to find a solution that just works well for everybody.

![with_pv3](https://user-images.githubusercontent.com/31905376/123179035-cfb02380-d488-11eb-8d1e-b60ec7db8ac3.gif)
